# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08f13a9d55757031f496ce3c2ae35ad3750b23bcd7256713f8c83a0adcf569b2a685cd315120c76ca923ad83207102b3261cf44bacf20cff8ebb62e2050d4502

test:
  secret_key_base: b895815fbc4ce32ff11ed75f963263ab4671de7d4ffad445f69b064c32f6ec791a4280c122a5251b0e5f928ab0d7ddf1ba0fc81016f3b8bff77390527bd03492

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
